# Generated by Django 5.1.3 on 2024-11-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upsated',
            new_name='updated',
        ),
    ]
